### ISSUE TITLE
[Feat] 당근마켓  - 상품 Detail UI

### ISSUE THREAD

**Issue by 0lynny** [0lynny/Carrot-Market-iOS#5]
## Issue

당근마켓  -  상품 Detail UI

## To-do

- [x] 테이블뷰 셀 누르면 이동하게 하기
- [x] PageControl로 이미지 여러장 스크롤하게 하기
- [x] 좋아요 버튼 이벤트 발생시키기
