### ISSUE TITLE
[Feat]상품 Detail 서버붙이기

### ISSUE THREAD

**Issue by 0lynny** [0lynny/Carrot-Market-iOS#7]
## Issue

당근마켓  -  상품 Detail 서버 붙이기

## To-do

- [x] 상품 상세 페이지 조회 API
- [x] 상품 좋아요 등록 및 취소
- [x] 상품 판매 상태 변경 요청
